#!/usr/bin/env python3
"""
Generate RoundtripTestData.kt and updated TtsSpeechRoundtripTest.kt
with ~1000-word texts for all 14 supported languages.
"""
import os

OUT_DIR = "app/src/test/java/com/aitorpazos/pipertts"

# ── Language configurations ──────────────────────────────────────────
LANGS = {
    "en": {
        "label": "english",
        "voice": "en-us",
        "model": "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/amy/medium/en_US-amy-medium.onnx",
        "config": "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/amy/medium/en_US-amy-medium.onnx.json",
        "mf": "en_US-amy-medium.onnx",
        "cf": "en_US-amy-medium.onnx.json",
        "vosk": "https://alphacephei.com/vosk/models/vosk-model-small-en-us-0.15.zip",
        "vd": "vosk-en",
    },
    "es": {
        "label": "spanish",
        "voice": "es",
        "model": "https://huggingface.co/rhasspy/piper-voices/resolve/main/es/es_ES/davefx/medium/es_ES-davefx-medium.onnx",
        "config": "https://huggingface.co/rhasspy/piper-voices/resolve/main/es/es_ES/davefx/medium/es_ES-davefx-medium.onnx.json",
        "mf": "es_ES-davefx-medium.onnx",
        "cf": "es_ES-davefx-medium.onnx.json",
        "vosk": "https://alphacephei.com/vosk/models/vosk-model-small-es-0.42.zip",
        "vd": "vosk-es",
    },
    "fr": {
        "label": "french",
        "voice": "fr-fr",
        "model": "https://huggingface.co/rhasspy/piper-voices/resolve/main/fr/fr_FR/siwis/medium/fr_FR-siwis-medium.onnx",
        "config": "https://huggingface.co/rhasspy/piper-voices/resolve/main/fr/fr_FR/siwis/medium/fr_FR-siwis-medium.onnx.json",
        "mf": "fr_FR-siwis-medium.onnx",
        "cf": "fr_FR-siwis-medium.onnx.json",
        "vosk": "https://alphacephei.com/vosk/models/vosk-model-small-fr-0.22.zip",
        "vd": "vosk-fr",
    },
    "de": {
        "label": "german",
        "voice": "de",
        "model": "https://huggingface.co/rhasspy/piper-voices/resolve/main/de/de_DE/thorsten/medium/de_DE-thorsten-medium.onnx",
        "config": "https://huggingface.co/rhasspy/piper-voices/resolve/main/de/de_DE/thorsten/medium/de_DE-thorsten-medium.onnx.json",
        "mf": "de_DE-thorsten-medium.onnx",
        "cf": "de_DE-thorsten-medium.onnx.json",
        "vosk": "https://alphacephei.com/vosk/models/vosk-model-small-de-0.15.zip",
        "vd": "vosk-de",
    },
    "it": {
        "label": "italian",
        "voice": "it",
        "model": "https://huggingface.co/rhasspy/piper-voices/resolve/main/it/it_IT/riccardo/x_low/it_IT-riccardo-x_low.onnx",
        "config": "https://huggingface.co/rhasspy/piper-voices/resolve/main/it/it_IT/riccardo/x_low/it_IT-riccardo-x_low.onnx.json",
        "mf": "it_IT-riccardo-x_low.onnx",
        "cf": "it_IT-riccardo-x_low.onnx.json",
        "vosk": "https://alphacephei.com/vosk/models/vosk-model-small-it-0.22.zip",
        "vd": "vosk-it",
    },
    "pt": {
        "label": "portuguese",
        "voice": "pt-br",
        "model": "https://huggingface.co/rhasspy/piper-voices/resolve/main/pt/pt_BR/faber/medium/pt_BR-faber-medium.onnx",
        "config": "https://huggingface.co/rhasspy/piper-voices/resolve/main/pt/pt_BR/faber/medium/pt_BR-faber-medium.onnx.json",
        "mf": "pt_BR-faber-medium.onnx",
        "cf": "pt_BR-faber-medium.onnx.json",
        "vosk": "https://alphacephei.com/vosk/models/vosk-model-small-pt-0.3.zip",
        "vd": "vosk-pt",
    },
    "nl": {
        "label": "dutch",
        "voice": "nl",
        "model": "https://huggingface.co/rhasspy/piper-voices/resolve/main/nl/nl_NL/mls/medium/nl_NL-mls-medium.onnx",
        "config": "https://huggingface.co/rhasspy/piper-voices/resolve/main/nl/nl_NL/mls/medium/nl_NL-mls-medium.onnx.json",
        "mf": "nl_NL-mls-medium.onnx",
        "cf": "nl_NL-mls-medium.onnx.json",
        "vosk": "https://alphacephei.com/vosk/models/vosk-model-small-nl-0.22.zip",
        "vd": "vosk-nl",
    },
    "pl": {
        "label": "polish",
        "voice": "pl",
        "model": "https://huggingface.co/rhasspy/piper-voices/resolve/main/pl/pl_PL/darkman/medium/pl_PL-darkman-medium.onnx",
        "config": "https://huggingface.co/rhasspy/piper-voices/resolve/main/pl/pl_PL/darkman/medium/pl_PL-darkman-medium.onnx.json",
        "mf": "pl_PL-darkman-medium.onnx",
        "cf": "pl_PL-darkman-medium.onnx.json",
        "vosk": "https://alphacephei.com/vosk/models/vosk-model-small-pl-0.22.zip",
        "vd": "vosk-pl",
    },
    "ru": {
        "label": "russian",
        "voice": "ru",
        "model": "https://huggingface.co/rhasspy/piper-voices/resolve/main/ru/ru_RU/denis/medium/ru_RU-denis-medium.onnx",
        "config": "https://huggingface.co/rhasspy/piper-voices/resolve/main/ru/ru_RU/denis/medium/ru_RU-denis-medium.onnx.json",
        "mf": "ru_RU-denis-medium.onnx",
        "cf": "ru_RU-denis-medium.onnx.json",
        "vosk": "https://alphacephei.com/vosk/models/vosk-model-small-ru-0.22.zip",
        "vd": "vosk-ru",
    },
    "uk": {
        "label": "ukrainian",
        "voice": "uk",
        "model": "https://huggingface.co/rhasspy/piper-voices/resolve/main/uk/uk_UA/ukrainian_tts/medium/uk_UA-ukrainian_tts-medium.onnx",
        "config": "https://huggingface.co/rhasspy/piper-voices/resolve/main/uk/uk_UA/ukrainian_tts/medium/uk_UA-ukrainian_tts-medium.onnx.json",
        "mf": "uk_UA-ukrainian_tts-medium.onnx",
        "cf": "uk_UA-ukrainian_tts-medium.onnx.json",
        "vosk": "https://alphacephei.com/vosk/models/vosk-model-small-uk-v3-nano.zip",
        "vd": "vosk-uk",
    },
    "ca": {
        "label": "catalan",
        "voice": "ca",
        "model": "https://huggingface.co/rhasspy/piper-voices/resolve/main/ca/ca_ES/upc_ona/medium/ca_ES-upc_ona-medium.onnx",
        "config": "https://huggingface.co/rhasspy/piper-voices/resolve/main/ca/ca_ES/upc_ona/medium/ca_ES-upc_ona-medium.onnx.json",
        "mf": "ca_ES-upc_ona-medium.onnx",
        "cf": "ca_ES-upc_ona-medium.onnx.json",
        "vosk": "https://alphacephei.com/vosk/models/vosk-model-small-ca-0.4.zip",
        "vd": "vosk-ca",
    },
    "sv": {
        "label": "swedish",
        "voice": "sv",
        "model": "https://huggingface.co/rhasspy/piper-voices/resolve/main/sv/sv_SE/nst/medium/sv_SE-nst-medium.onnx",
        "config": "https://huggingface.co/rhasspy/piper-voices/resolve/main/sv/sv_SE/nst/medium/sv_SE-nst-medium.onnx.json",
        "mf": "sv_SE-nst-medium.onnx",
        "cf": "sv_SE-nst-medium.onnx.json",
        "vosk": "https://alphacephei.com/vosk/models/vosk-model-small-sv-rhasspy-0.15.zip",
        "vd": "vosk-sv",
    },
    "tr": {
        "label": "turkish",
        "voice": "tr",
        "model": "https://huggingface.co/rhasspy/piper-voices/resolve/main/tr/tr_TR/dfki/medium/tr_TR-dfki-medium.onnx",
        "config": "https://huggingface.co/rhasspy/piper-voices/resolve/main/tr/tr_TR/dfki/medium/tr_TR-dfki-medium.onnx.json",
        "mf": "tr_TR-dfki-medium.onnx",
        "cf": "tr_TR-dfki-medium.onnx.json",
        "vosk": "https://alphacephei.com/vosk/models/vosk-model-small-tr-0.3.zip",
        "vd": "vosk-tr",
    },
    "vi": {
        "label": "vietnamese",
        "voice": "vi-vn-x-south",
        "model": "https://huggingface.co/rhasspy/piper-voices/resolve/main/vi/vi_VN/25hours_single/low/vi_VN-25hours_single-low.onnx",
        "config": "https://huggingface.co/rhasspy/piper-voices/resolve/main/vi/vi_VN/25hours_single/low/vi_VN-25hours_single-low.onnx.json",
        "mf": "vi_VN-25hours_single-low.onnx",
        "cf": "vi_VN-25hours_single-low.onnx.json",
        "vosk": "https://alphacephei.com/vosk/models/vosk-model-small-vn-0.4.zip",
        "vd": "vosk-vi",
    },
}

print(f"Configured {len(LANGS)} languages: {', '.join(LANGS.keys())}")
